library(ggplot2)
library(MASS)
set.seed(123)

#read the association file generated by GEMMA
df=read.table('result.assoc.txt',header=T)

#calculate the final adjusted p-value
df$q_wald <- p.adjust(df$p_wald,method = 'BH')
df$q_lrt <- p.adjust(df$p_lrt,method = 'BH')
df$q_score <- p.adjust(df$p_score,method = 'BH')
df$q=apply(df[,16:18],1,min)

#thinned the non-significant data points (p >= 5e-8)
threshold <- 5e-8
df_low <- df[df$q >= threshold, ]  
df_high <- df[df$q < threshold, ]
dens <- kde2d(df_low$ps, df_low$q, n = 100)
get_density_at_point <- function(x, y, dens) {
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ix[ix < 1] <- 1; iy[iy < 1] <- 1
  ix[ix > length(dens$x)] <- length(dens$x)
  iy[iy > length(dens$y)] <- length(dens$y)
  
  return(dens$z[cbind(ix, iy)])
}
point_densities <- get_density_at_point(df_low$ps, df_low$q, dens)
dens_norm <- (point_densities - min(point_densities)) / (max(point_densities) - min(point_densities))
weights <- 1 - dens_norm + 1e-6
weights_norm <- weights / sum(weights)
target_n <- round(nrow(df_low) * 0.02)
selected_indices <- sample(seq_len(nrow(df_low)), size = target_n, replace = FALSE, prob = weights_norm)
df_low_thinned <- df_low[selected_indices, ]
df_final <- rbind(df_low_thinned, df_high)

#draw the manhattan plot
ggplot(df_final, aes(x=ps, y=-log10(q), color=factor(chr))) + 
  geom_point(alpha=0.7) +
  scale_color_manual(values=c("grey"))+
  theme_minimal() +
  ggtitle("Manhattan Plot of GWAS Results") +
  xlab("Chromosome Position") +
  ylab("-log10(p-value)") +
  theme(legend.position="none") +
  geom_hline(yintercept = -log10(5e-8), color="red", linetype="dashed")
